defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  name: whoops_development

test:
  <<: *defaults
  name: whoops_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>